const express = require('express');
const router = express.Router(); 
const { Op } = require('sequelize'); 
const { restoreUser, requireAuth } = require('../../utils/auth.js');


router.get('/api/spots', async (req, res) => {
    const allSpots = await Spot.findAll(); 

    //! Is there a need to loop and ammend avgRating and preview imge to end of each individual spot obj ? TBD
    return res.status(200).json({
        allSpots,
        //! avgRating,
        //! previewImg
    });
}); 

router.get('/api/spots/current', restoreUser, requireAuth, async (req, res) => {
    const currentUserId = req.user.id;

    const currentSpots = await Spot.findAll({
        where: {
            ownerId: currentUserId,
        },
    });

    return res.status(200).json({
        Spots: currentSpots,
        //! avgRating,
        //! previewImg
    });

}); 

router.get('/api/spots/:spotId', async (req, res) => {
    const spotById = await Spot.findByPk(req.params.spotId); 

    if (!spotById) {
        return res.status(404).json({ message: "Spot couldn't be found" })
    }

    return res.status(200).json({
        spotById,
        //! numReviews:
        //! avgStarRating:
        //! Spotimage:
        //! Owner:
    });

});

router.post('/api/spots', restoreUser, requireAuth, async (req, res) => {
    try {
        const { address, city, state, country, lat, lng, name, description, price } = req.body; 

    const newSpot = await Spot.create({
        ownerId: req.user.id,
        address, 
        city, 
        state, 
        country, 
        lat, 
        lng, 
        name, 
        description, 
        price,
    }); 

    res.status(201).json(newSpot); 
    } catch (e) {
        res.status(400).json({
            message: "Bad Request", // (or "Validation error" if generated by Sequelize),
            errors: {
              address: "Street address is required",
              city: "City is required",
              state: "State is required",
              country: "Country is required",
              lat: "Latitude must be within -90 and 90",
              lng: "Longitude must be within -180 and 180",
              name: "Name must be less than 50 characters",
              description: "Description is required",
              price: "Price per day must be a positive number"
            }
          })
    } 
}) 

router.post('/api/spots/:spotId/images', restoreUser, requireAuth, async (req, res) => { 
    const { url, preview } = req.body;

    const spotById = await Spot.findByPk(req.params.spotId); 
    
    if (!spotById) {
        return res.status(404).json({ message: "Spot couldn't be found" })
    } 

    if (spotById.ownerId !== req.user.id) {
        return res.status(403).json({
            message: "Spot must belong to user"
        })
    }
    //! import SpotImage model
    const newImage = await SpotImage.create({
        url: req.body.url,
        preview: req.body.preview,
        spotId: spotById.id //! is this needed?
    }); 
    //! do we need to specify attributes(where)to exclude spotId ?
    res.status(201).json(newImage);
})

router.put('/api/spots/:spotId/', restoreUser, requireAuth, async (req, res) => {
    try {
        const { address, city, state, country, lat, lng, name, description, price } = req.body; 
        
        let spotById = await Spot.findByPk(req.params.spotId); 
        
        if (!spotById) {
            return res.status(404).json({ message: "Spot couldn't be found" })
        } 
    
        if (spotById.ownerId !== req.user.id) {
            return res.status(403).json({
                message: "Spot must belong to user"
            })
        }

        spotById = await Spot.update({
        // ownerId: req.user.id,
        address: req.body.address,
        city: req.body.city, 
        state: req.body.state, 
        country: req.body.country, 
        lat: req.body.lat, 
        lng: req.body.lng, 
        name: req.body.name, 
        description: req.body.description, 
        price: req.body.price, 
        //...req.body
    }); 

    res.status(200).json(spotById); 
    } catch (e) {
        res.status(400).json({
            message: "Bad Request", // (or "Validation error" if generated by Sequelize),
            errors: {
              address: "Street address is required",
              city: "City is required",
              state: "State is required",
              country: "Country is required",
              lat: "Latitude must be within -90 and 90",
              lng: "Longitude must be within -180 and 180",
              name: "Name must be less than 50 characters",
              description: "Description is required",
              price: "Price per day must be a positive number"
            }
          })
    } 
    
}) 

router.delete('/api/spots/:spotId', restoreUser, requireAuth, async (req, res) => { 
    const spotById = await Spot.findByPk(req.params.spotId);

    if (!spotById) {
        return res.status(404).json({ message: "Spot couldn't be found" })
    }
    
    if (spotById.ownerId !== req.user.id) {
        return res.status(403).json({
            message: "Spot must belong to user"
        })
    } 

    await spotById.destroy();

    return res.status(200).json({ message: " Successfully deleted" });
})










module.exports = router;